begin;

-- Compatibility migration: reuse the existing CampusAI college schema.

create table if not exists public.college_nirf_rankings (
  nirf_ranking_id bigint generated by default as identity primary key,
  college_id integer not null references public.colleges(college_id) on delete cascade,
  institution_id text,
  ranking_year integer not null check (ranking_year between 2016 and 2100),
  category text not null default 'engineering',
  exact_rank integer check (exact_rank is null or exact_rank > 0),
  rank_band text,
  overall_score numeric(6, 3),
  tlr_score numeric(6, 3),
  rpc_score numeric(6, 3),
  graduation_outcomes_score numeric(6, 3),
  outreach_inclusivity_score numeric(6, 3),
  perception_score numeric(6, 3),
  source_url text not null,
  last_verified_at timestamp with time zone not null default now(),
  created_at timestamp with time zone not null default now(),
  updated_at timestamp with time zone not null default now(),
  constraint college_nirf_rankings_rank_required
    check (exact_rank is not null or nullif(trim(rank_band), '') is not null),
  constraint college_nirf_rankings_unique_year_category
    unique (college_id, ranking_year, category)
);

create table if not exists public.college_accreditations (
  college_accreditation_id bigint generated by default as identity primary key,
  college_id integer not null references public.colleges(college_id) on delete cascade,
  accreditation_body text not null,
  accreditation_status text not null default 'accredited',
  grade text,
  score numeric(5, 2),
  cycle text,
  valid_from date,
  valid_upto date,
  details jsonb not null default '{}'::jsonb,
  source_url text not null,
  last_verified_at timestamp with time zone not null default now(),
  created_at timestamp with time zone not null default now(),
  updated_at timestamp with time zone not null default now(),
  constraint college_accreditations_valid_dates
    check (valid_upto is null or valid_from is null or valid_upto >= valid_from)
);

create table if not exists public.college_official_links (
  college_id integer primary key references public.colleges(college_id) on delete cascade,
  official_website text,
  admissions_url text,
  placements_url text,
  mandatory_disclosure_url text,
  nirf_disclosure_url text,
  contact_url text,
  verification_status text not null default 'pending',
  source_url text,
  last_verified_at timestamp with time zone,
  created_at timestamp with time zone not null default now(),
  updated_at timestamp with time zone not null default now(),
  constraint college_official_links_verification_status
    check (verification_status in ('pending', 'verified', 'rejected', 'unavailable'))
);

create table if not exists public.college_placement_statistics (
  placement_statistic_id bigint generated by default as identity primary key,
  college_id integer not null references public.colleges(college_id) on delete cascade,
  academic_year text not null,
  program_level text not null default 'ug',
  eligible_students integer check (eligible_students is null or eligible_students >= 0),
  students_placed integer check (students_placed is null or students_placed >= 0),
  students_higher_studies integer check (students_higher_studies is null or students_higher_studies >= 0),
  median_salary numeric(14, 2) check (median_salary is null or median_salary >= 0),
  average_salary numeric(14, 2) check (average_salary is null or average_salary >= 0),
  highest_salary numeric(14, 2) check (highest_salary is null or highest_salary >= 0),
  source_type text not null default 'official_disclosure',
  is_self_reported boolean not null default false,
  source_url text not null,
  last_verified_at timestamp with time zone not null default now(),
  created_at timestamp with time zone not null default now(),
  updated_at timestamp with time zone not null default now(),
  constraint college_placement_statistics_unique_period
    unique (college_id, academic_year, program_level)
);

alter table public.branch_accreditations
  add column if not exists tier character varying,
  add column if not exists washington_accord_eligible boolean,
  add column if not exists source_url text,
  add column if not exists last_verified_at timestamp with time zone;

alter table public.college_images
  add column if not exists source_url text,
  add column if not exists usage_status character varying default 'permission_required',
  add column if not exists attribution text,
  add column if not exists last_verified_at timestamp with time zone;

create index if not exists college_nirf_rankings_college_year_idx
  on public.college_nirf_rankings (college_id, ranking_year desc);
create index if not exists college_accreditations_college_body_idx
  on public.college_accreditations (college_id, accreditation_body);
create index if not exists college_placement_statistics_college_year_idx
  on public.college_placement_statistics (college_id, academic_year desc);
create index if not exists branch_accreditations_source_idx
  on public.branch_accreditations (college_branch_id, accreditation_body);
create index if not exists college_images_active_order_idx
  on public.college_images (college_id, is_active, display_order);

alter table public.college_nirf_rankings enable row level security;
alter table public.college_accreditations enable row level security;
alter table public.college_official_links enable row level security;
alter table public.college_placement_statistics enable row level security;

create policy "Public can read NIRF rankings"
  on public.college_nirf_rankings for select using (true);
create policy "Public can read college accreditations"
  on public.college_accreditations for select using (true);
create policy "Public can read verified official links"
  on public.college_official_links for select using (verification_status = 'verified');
create policy "Public can read placement statistics"
  on public.college_placement_statistics for select using (true);

commit;
