begin;

create table if not exists public.tnea_college_intakes (
  intake_id bigint generated by default as identity primary key,
  admission_year smallint not null check (admission_year between 2020 and 2100),
  college_code text not null,
  college_name text not null,
  branch_code text not null,
  branch_name text not null,
  oc_seats integer not null default 0 check (oc_seats >= 0),
  bc_seats integer not null default 0 check (bc_seats >= 0),
  bcm_seats integer not null default 0 check (bcm_seats >= 0),
  mbc_seats integer not null default 0 check (mbc_seats >= 0),
  sc_seats integer not null default 0 check (sc_seats >= 0),
  sca_seats integer not null default 0 check (sca_seats >= 0),
  st_seats integer not null default 0 check (st_seats >= 0),
  source_url text not null,
  source_published_on date,
  last_verified_at timestamp with time zone not null default now(),
  created_at timestamp with time zone not null default now(),
  updated_at timestamp with time zone not null default now(),
  constraint tnea_college_intakes_unique_offer
    unique (admission_year, college_code, branch_code)
);

comment on table public.tnea_college_intakes is
  'Official TNEA seat matrix by admission year, college, branch, and community.';

create table if not exists public.tnea_merit_ranks (
  merit_rank_id bigint generated by default as identity primary key,
  admission_year smallint not null check (admission_year between 2020 and 2100),
  stream text not null default 'general_academic',
  general_rank integer not null check (general_rank > 0),
  aggregate_mark numeric(6, 3) not null check (aggregate_mark between 0 and 200),
  community text not null check (community in ('OC', 'BC', 'BCM', 'MBC', 'SC', 'SCA', 'ST')),
  community_rank integer check (community_rank is null or community_rank > 0),
  source_url text not null,
  is_provisional boolean not null default true,
  last_verified_at timestamp with time zone not null default now(),
  created_at timestamp with time zone not null default now(),
  updated_at timestamp with time zone not null default now(),
  constraint tnea_merit_ranks_unique_general_rank
    unique (admission_year, stream, general_rank)
);

comment on table public.tnea_merit_ranks is
  'Privacy-minimized TNEA merit list. Application numbers are intentionally excluded.';

create index if not exists tnea_college_intakes_year_college_idx
  on public.tnea_college_intakes (admission_year desc, college_code);
create index if not exists tnea_college_intakes_year_branch_idx
  on public.tnea_college_intakes (admission_year desc, branch_code);
create index if not exists tnea_merit_ranks_year_mark_idx
  on public.tnea_merit_ranks (admission_year desc, aggregate_mark desc);
create index if not exists tnea_merit_ranks_year_community_rank_idx
  on public.tnea_merit_ranks (admission_year desc, community, community_rank);

alter table public.tnea_college_intakes enable row level security;
alter table public.tnea_merit_ranks enable row level security;

drop policy if exists "Public can read TNEA college intakes" on public.tnea_college_intakes;
create policy "Public can read TNEA college intakes"
  on public.tnea_college_intakes for select using (true);

drop policy if exists "Public can read TNEA merit ranks" on public.tnea_merit_ranks;
create policy "Public can read TNEA merit ranks"
  on public.tnea_merit_ranks for select using (true);

commit;
